language: java
jdk:
  - oraclejdk8
dist: trusty

before_install:
  - chmod +x gradlew

script:
  - echo "script"

jobs:
  include:
    - stage: Custom Testing
      name: Unit-Testing
      script: ./gradlew clean test --info
    - name: Integration-Testing
      script: echo "Integration-Testing_script"